export class ProductCategory {
  asset_classification: number;
  asset_name: string;
  asset_status: number;
  asset_unique_number: number;
  battery_percentage: number;
  breadth_cms: number;
  category: number;
  category_name:string;
  client_id: number;
  created_by: number;
  height_cms: number;
  id: number;
  is_back_cover_present: string;
  is_charger_present: string;
  is_connector_present: string;
  is_headphone_present: string;
  is_manual_entry: number;
  is_manual_present: string;
  is_original_box_present:string;
  is_shrinked_wrapped: string;
  length_cms: number;
  location: string;
  manufacturer: string;
  procurement_id: number;
  procurement_price: number;
  product_color: string;
  product_grade: number;
  responsible_technician_id: number;
  sale_price: number;
  sku: string;
  status_name: string;
  sub_category: number;
  suggested_price: number;
  video_url: string;
  warranty_status: number;
  weight_gms: number;
}
